yamoney.register_store("default", "default_cobble.png^yamoney_5e.png", "Minetest Default Store", {
	{"default:stone 8", 0.50},
	{"default:wood 8", 1},
	{"default:tree 2", 1},
	{"default:iron_lump 8", 10},
	{"default:copper_lump 8", 15},
	{"default:mese_crystal 2", 40},
	{"default:diamond 2", 45},
	{"default:coal_lump 8", 5},
	
	{"default:axe_stone", 1.50},
	{"default:pick_stone", 1.50},
	{"default:shovel_stone", 1.50},
	{"default:sword_stone", 1.50},
	{"default:axe_bronze", 3.80},
	{"default:pick_bronze", 3.80},
	{"default:shovel_bronze", 3.80},
	{"default:sword_bronze", 3.80},
	
	{"default:grass_1 16", 0.60},
	{"default:dry_grass_1 16", 0.60},
	{"default:sapling 8", 0.99},
	{"default:junglesapling 8", 1.10},
	{"default:pine_sapling", 1.10},
	{"default:acacia_sapling", 1.10},
	{"default:aspen_sapling", 1.10},
})